# Generated by Django 4.1.9 on 2023-06-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
